name: Validere pull request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  valid-pull-request:
    name: Validere pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sette opp Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
      - name: Installere dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Kjøre linter
        run: npm run lint
      - name: Kjøre bygg
        run: npm run build
