name: Validere pull request
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    valid-pull-request:
        name: Validere pull request
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Installere dependencies
              run: yarn
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre linter
              run: yarn lint
            - name: Valider typescript
              run: yarn ts-check
            - name: Kjøre enhetstester
              run: yarn test
            - name: Laster opp screenshots dersom de visuelle regresjonstestene feiler
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: visual-regression-screenshots
                  path: src/__tests__/__image_snapshots__/__diff_output__/
            - name: Kjør E2E-tester
              uses: cypress-io/github-action@v4
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  start: yarn start:e2e
                  wait-on: 'http://localhost:8081'
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - name: Kjøre bygg
              run: npm run build
